# -*- coding: utf-8 -*-
"""MusicRecSYS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Mv7JgASzY0Vjze_B4pI_ymjrlNiawvg

# NLP -  Music Recommendation System

## Loading and Cleaning the data

#### Column names and description

| Variable                   | Class      | Description |
|----------------------------|-----------|-------------|
| track_id                   | character | Song unique ID |
| track_name                 | character | Song Name |
| track_artist               | character | Song Artist |
| lyrics                     | character | Lyrics for the song |
| track_popularity           | double    | Song Popularity (0-100) where higher is better |
| track_album_id             | character | Album unique ID |
| track_album_name           | character | Song album name |
| track_album_release_date   | character | Date when album released |
| playlist_name              | character | Name of playlist |
| playlist_id                | character | Playlist ID |
| playlist_genre             | character | Playlist genre |
| playlist_subgenre          | character | Playlist subgenre |
| danceability               | double    | Danceability describes how suitable a track is for dancing based on tempo, rhythm stability, beat strength, and regularity (0.0 = least, 1.0 = most) |
| energy                     | double    | Energy (0.0–1.0) represents intensity and activity; higher values feel fast, loud, and noisy |
| key                        | double    | Estimated key of the track (0 = C, 1 = C♯/D♭, etc.; -1 if no key detected) |
| loudness                   | double    | Overall loudness in decibels (dB), typically between -60 and 0 |
| mode                       | double    | Modality of track: major = 1, minor = 0 |
| speechiness                | double    | Detects spoken words (closer to 1.0 = more speech-like; >0.66 mostly speech) |
| acousticness               | double    | Confidence (0.0–1.0) that the track is acoustic |
| instrumentalness           | double    | Likelihood track has no vocals (closer to 1.0 = instrumental) |
| liveness                   | double    | Detects audience presence; >0.8 suggests live performance |
| valence                    | double    | Musical positivity (0.0–1.0; higher = happier) |
| tempo                      | double    | Estimated tempo in beats per minute (BPM) |
| duration_ms                | double    | Duration of song in milliseconds |
| language                   | character | Language of the lyrics |

#### Loading and Reading Data
"""

import pandas as pd

df_spotify = pd.read_csv("Audio_featuresandlyrics.csv")
# getting column names
df_spotify.columns

print(df_spotify['playlist_genre'].unique())
df_spotify.head(2)

"""#### Cleaning the dataframe"""

# removing 'track_album_id', 'playlist_name', 'playlist_id'
df_spotifyclean = df_spotify[['track_id', 'track_name', 'track_artist', 'lyrics', 'track_popularity','track_album_name',
'track_album_release_date', 'playlist_genre', 'playlist_subgenre', 'danceability', 'energy', 'key', 'loudness',
'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo','duration_ms', 'language']]
# keeping rows with language = english and removing rows with genre = latin
df_spotifyclean = df_spotifyclean.loc[(df_spotifyclean['language'] == 'en') & (df_spotifyclean['playlist_genre'] != 'latin')]
# removing tracks with no lyrics
df_spotifyclean= df_spotifyclean.loc[df_spotifyclean['lyrics'] != 'Lyrics for this song have yet to be released. Please check back once the song has been released.']
# index reset
df_spotifyclean = df_spotifyclean.reset_index(drop=True)
print('Dimensions of cleaned Dataframe:', df_spotifyclean.shape)

df_spotifyclean.head()

"""<h1>Lyrical Similarity</h1>"""

# clean the lyrics
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-z\s]", "", text)  # remove punctuation/numbers
    text = re.sub(r"\s+", " ", text).strip()
    return text

df_spotifyclean["clean_lyrics"] = df_spotifyclean["lyrics"].apply(clean_text)

# TF-IDF vectorizer of lyrics
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1, 2),   # bigrams included
    max_features=5000
)

tfidf_matrix = vectorizer.fit_transform(df_spotifyclean["clean_lyrics"])

# compute similarity matrix using cosine similarity
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tfidf_matrix)

"""<h1>Thematic Coherence</h1>"""

# use the elbow method to determine the optimal number of clusters
X = tfidf_matrix

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

inertia = []

for k in range(2, 15):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(2, 15), inertia, marker='o')
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia")
plt.title("Elbow Method for Optimal k")
plt.show()

"""K = 10 seems like approximately the elbow"""

# cluster with 10 clusters
NUM_CLUSTERS = 10

kmeans = KMeans(n_clusters=NUM_CLUSTERS, random_state=42)
df_spotifyclean["cluster"] = kmeans.fit_predict(tfidf_matrix)

# inspect clusters for understanding
def show_cluster_examples(cluster_id, n=5):
    return df_spotifyclean[df_spotifyclean["cluster"] == cluster_id][
        ["track_name", "track_artist"]
    ].head(n)

show_cluster_examples(0)

show_cluster_examples(1)

show_cluster_examples(2)

show_cluster_examples(3)

show_cluster_examples(4)

show_cluster_examples(5)

show_cluster_examples(6)

show_cluster_examples(7)

show_cluster_examples(8)

show_cluster_examples(9)

# Label clusters
import numpy as np

terms = vectorizer.get_feature_names_out()

def get_top_terms_per_cluster(kmeans, n_terms=10):
    centroids = kmeans.cluster_centers_

    for i, center in enumerate(centroids):
        top_indices = center.argsort()[::-1][:n_terms]
        top_words = [terms[j] for j in top_indices]

        print(f"Cluster {i}: {', '.join(top_words)}")

get_top_terms_per_cluster(kmeans, n_terms=10)

# plot clusters
from sklearn.decomposition import PCA

pca = PCA(n_components=2, random_state=42)
X_2d = pca.fit_transform(tfidf_matrix.toarray())

df_spotifyclean["x"] = X_2d[:, 0]
df_spotifyclean["y"] = X_2d[:, 1]

plt.figure(figsize=(10,7))

scatter = plt.scatter(
    df_spotifyclean["x"],
    df_spotifyclean["y"],
    c=df_spotifyclean["cluster"],
    cmap="tab10",
    alpha=0.6
)

plt.title("Song Clusters (TF-IDF + KMeans)")
plt.xlabel("Component 1")
plt.ylabel("Component 2")

plt.legend(*scatter.legend_elements(), title="Clusters")
plt.show()

"""<h1>Emotional Arc</h1>"""

# create emotion labels

def get_emotion(row):
    if row["valence"] > 0.6 and row["energy"] > 0.6:
        return "happy_energetic"
    elif row["valence"] > 0.6:
        return "happy_calm"
    elif row["energy"] > 0.6:
        return "intense"
    else:
        return "sad_calm"

df_spotifyclean["emotion"] = df_spotifyclean.apply(get_emotion, axis=1)

# define emotional arcs (playlist "story")
EMOTIONAL_ARCS = {
    "chill_to_hype": [
        "sad_calm",
        "happy_calm",
        "happy_energetic"
    ],
    "hype_to_chill": [
        "happy_energetic",
        "happy_calm",
        "sad_calm"
    ]
}

# sort songs by emotional progression

def apply_emotional_arc(df_subset, arc_name="chill_to_hype"):
    arc = EMOTIONAL_ARCS[arc_name]

    emotion_rank = {e: i for i, e in enumerate(arc)}

    df_subset = df_subset.copy()

    df_subset["emotion_rank"] = df_subset["emotion"].map(
        lambda x: emotion_rank.get(x, len(arc))
    )

    return df_subset.sort_values(
        ["emotion_rank", "energy"]
    )

"""<h1>Generate Playlist</h1>"""

# song lookup function (song name to song index)

def get_song_index(song_name):
    matches = df_spotifyclean[
        df_spotifyclean["track_name"].str.lower() == song_name.lower()
    ]

    if len(matches) == 0:
        return None

    return matches.index[0]

# use similarity matrix to get similar songs
def get_similar_songs(song_idx, top_n=50):
    sim_scores = similarity_matrix[song_idx]

    # sort by similarity (highest first)
    similar_indices = sim_scores.argsort()[::-1]

    # remove the song itself
    similar_indices = similar_indices[1:top_n+1]

    return df_spotifyclean.iloc[similar_indices]

# combine with thematic coherence
def get_clustered_candidates(song_idx, top_n=50):
    cluster_id = df_spotifyclean.loc[song_idx, "cluster"]

    cluster_df = df_spotifyclean[
        df_spotifyclean["cluster"] == cluster_id
    ]

    return cluster_df

# combine similarity and cluster
def get_recommendations(song_idx, top_n=30):
    cluster_df = get_clustered_candidates(song_idx)

    # compute similarity within cluster only
    cluster_indices = cluster_df.index

    scores = similarity_matrix[song_idx][cluster_indices]

    cluster_df = cluster_df.copy()
    cluster_df["similarity"] = scores

    return cluster_df.sort_values("similarity", ascending=False)

# generate recommendations, bringing together similarity, cluster, and emotional arc
def generate_playlist(song_name, top_n=15, arc="chill_to_hype"):

    # 1. get index
    song_idx = get_song_index(song_name)

    if song_idx is None:
        return "Song not found"

    # 2. get recommendations (similar + cluster filtered)
    recs = get_recommendations(song_idx, top_n=50)

    # 3. apply emotional arc
    recs = apply_emotional_arc(recs, arc_name=arc)

    # 4. return final playlist
    return recs.head(top_n)[[
        "track_name",
        "track_artist",
        "emotion",
        "cluster"
    ]]

# Test!
playlist = generate_playlist("Shape of You", top_n=10)

print(playlist)

"""<h1>Building UI</h1>"""

# export files for building UI in GitHub

import pickle

with open("music_recommender.pkl", "wb") as f:
    pickle.dump({
        "df": df_spotifyclean,
        "similarity_matrix": similarity_matrix,
        "EMOTIONAL_ARCS": EMOTIONAL_ARCS,
        "vectorizer": vectorizer,
        "kmeans": kmeans
    }, f)